export const DIVIPOLA_3: Record<string, string[]> = {
  "PUTUMAYO": [
    "COLÓN",
    "MOCOA",
    "ORITO",
    "PUERTO ASÍS",
    "PUERTO CAICEDO",
    "PUERTO GUZMÁN",
    "PUERTO LEGUÍZAMO",
    "SAN FRANCISCO",
    "SAN MIGUEL",
    "SANTIAGO",
    "SIBUNDOY",
    "VALLE DEL GUAMUEZ",
    "VILLAGARZÓN"
  ],
  "QUINDÍO": [
    "ARMENIA",
    "BUENAVISTA",
    "CALARCÁ",
    "CIRCASIA",
    "CÓRDOBA",
    "FILANDIA",
    "GÉNOVA",
    "LA TEBAIDA",
    "MONTENEGRO",
    "PIJAO",
    "QUIMBAYA",
    "SALENTO"
  ],
  "RISARALDA": [
    "APÍA",
    "BALBOA",
    "BELÉN DE UMBRÍA",
    "DOSQUEBRADAS",
    "GUÁTICA",
    "LA CELIA",
    "LA VIRGINIA",
    "MARSELLA",
    "MISTRATÓ",
    "PEREIRA",
    "PUEBLO RICO",
    "QUINCHÍA",
    "SANTA ROSA DE CABAL",
    "SANTUARIO"
  ],
  "SAN ANDRÉS Y PROVIDENCIA": [
    "PROVIDENCIA Y SANTA CATALINA ISLAS",
    "SAN ANDRÉS"
  ],
  "SANTANDER": [
    "AGUADA",
    "ALBANIA",
    "ARATOCA",
    "BARBOSA",
    "BARICHARA",
    "BARRANCABERMEJA",
    "BETULIA",
    "BOLÍVAR",
    "BUCARAMANGA",
    "CABRERA",
    "CALIFORNIA",
    "CAPITANEJO",
    "CARCASÍ",
    "CEPITÁ",
    "CERRITO",
    "CHARALÁ",
    "CHARTA",
    "CHIMA",
    "CHIPATÁ",
    "CIMITARRA",
    "CONCEPCIÓN",
    "CONFINES",
    "CONTRATACIÓN",
    "COROMORO",
    "CURITÍ",
    "EL CARMEN DE CHUCURÍ",
    "EL GUACAMAYO",
    "EL PEÑÓN",
    "EL PLAYÓN",
    "EL SOCORRO",
    "ENCINO",
    "ENCISO",
    "FLORIDABLANCA",
    "FLORIÁN",
    "GALÁN",
    "GIRÓN",
    "GUACA",
    "GUADALUPE",
    "GUAPOTÁ",
    "GUAVATÁ",
    "GÁMBITA",
    "GÜEPSA",
    "HATO",
    "JESÚS MARÍA",
    "JORDÁN",
    "LA BELLEZA",
    "LA PAZ",
    "LANDÁZURI",
    "LEBRIJA",
    "LOS SANTOS",
    "MACARAVITA",
    "MATANZA",
    "MOGOTES",
    "MOLAGAVITA",
    "MÁLAGA",
    "OCAMONTE",
    "OIBA",
    "ONZAGA",
    "PALMAR",
    "PALMAS DEL SOCORRO",
    "PIEDECUESTA",
    "PINCHOTE",
    "PUENTE NACIONAL",
    "PUERTO PARRA",
    "PUERTO WILCHES",
    "PÁRAMO",
    "RIONEGRO",
    "SABANA DE TORRES",
    "SAN ANDRÉS",
    "SAN BENITO",
    "SAN GIL",
    "SAN JOAQUÍN",
    "SAN JOSÉ DE MIRANDA",
    "SAN MIGUEL",
    "SAN VICENTE DE CHUCURÍ",
    "SANTA BÁRBARA",
    "SANTA HELENA DEL OPÓN",
    "SIMACOTA",
    "SUAITA",
    "SUCRE",
    "SURATÁ",
    "TONA",
    "VALLE DE SAN JOSÉ",
    "VETAS",
    "VILLANUEVA",
    "VÉLEZ",
    "ZAPATOCA"
  ],
  "SUCRE": [
    "BUENAVISTA",
    "CAIMITO",
    "CHALÁN",
    "COLOSÓ",
    "COROZAL",
    "COVEÑAS",
    "EL ROBLE",
    "GALERAS",
    "GUARANDA",
    "LA UNIÓN",
    "LOS PALMITOS",
    "MAJAGUAL",
    "MORROA",
    "OVEJAS",
    "SAMPUÉS",
    "SAN ANTONIO DE PALMITO",
    "SAN BENITO ABAD",
    "SAN JUAN DE BETULIA",
    "SAN MARCOS",
    "SAN ONOFRE",
    "SAN PEDRO",
    "SINCELEJO",
    "SINCÉ",
    "SUCRE",
    "TOLÚ",
    "TOLÚ VIEJO"
  ],
  "TOLIMA": [
    "ALPUJARRA",
    "ALVARADO",
    "AMBALEMA",
    "ANZOÁTEGUI",
    "ARMERO",
    "ATACO",
    "CAJAMARCA",
    "CARMEN DE APICALÁ",
    "CASABIANCA",
    "CHAPARRAL",
    "COELLO",
    "COYAIMA",
    "CUNDAY",
    "DOLORES",
    "EL ESPINAL",
    "FALÁN",
    "FLANDES",
    "FRESNO",
    "GUAMO",
    "HERVEO",
    "HONDA",
    "IBAGUÉ",
    "ICONONZO",
    "LÉRIDA",
    "LÍBANO",
    "MARIQUITA",
    "MELGAR",
    "MURILLO",
    "NATAGAIMA",
    "ORTEGA",
    "PALOCABILDO",
    "PIEDRAS",
    "PLANADAS",
    "PRADO",
    "PURIFICACIÓN",
    "RIOBLANCO",
    "RONCESVALLES",
    "ROVIRA",
    "SALDAÑA",
    "SAN ANTONIO",
    "SAN LUIS",
    "SANTA ISABEL",
    "SUÁREZ",
    "VALLE DE SAN JUAN",
    "VENADILLO",
    "VILLAHERMOSA",
    "VILLARRICA"
  ],
  "VALLE DEL CAUCA": [
    "ALCALÁ",
    "ANDALUCÍA",
    "ANSERMANUEVO",
    "ARGELIA",
    "BOLÍVAR",
    "BUENAVENTURA",
    "BUGA",
    "BUGALAGRANDE",
    "CAICEDONIA",
    "CALI",
    "CALIMA",
    "CANDELARIA",
    "CARTAGO",
    "DAGUA",
    "EL CAIRO",
    "EL CERRITO",
    "EL DOVIO",
    "EL ÁGUILA",
    "FLORIDA",
    "GINEBRA",
    "GUACARÍ",
    "JAMUNDÍ",
    "LA CUMBRE",
    "LA UNIÓN",
    "LA VICTORIA",
    "OBANDO",
    "PALMIRA",
    "PRADERA",
    "RESTREPO",
    "RIOFRÍO",
    "ROLDANILLO",
    "SAN PEDRO",
    "SEVILLA",
    "TORO",
    "TRUJILLO",
    "TULUÁ",
    "ULLOA",
    "VERSALLES",
    "VIJES",
    "YOTOCO",
    "YUMBO",
    "ZARZAL"
  ],
  "VAUPÉS": [
    "CARURÚ",
    "MITÚ",
    "TARAIRA"
  ],
  "VICHADA": [
    "CUMARIBO",
    "LA PRIMAVERA",
    "PUERTO CARREÑO",
    "SANTA ROSALÍA"
  ]
};
