export const DIVIPOLA_2: Record<string, string[]> = {
  "CHOCÓ": [
    "ACANDÍ",
    "ALTO BAUDÓ",
    "BAGADÓ",
    "BAHÍA SOLANO",
    "BAJO BAUDÓ",
    "BOJAYÁ",
    "CANTÓN DE SAN PABLO",
    "CONDOTO",
    "CÉRTEGUI",
    "EL ATRATO",
    "EL CARMEN DE ATRATO",
    "EL CARMEN DEL DARIÉN",
    "ISTMINA",
    "JURADÓ",
    "LITORAL DE SAN JUAN",
    "LLORÓ",
    "MEDIO ATRATO",
    "MEDIO BAUDÓ",
    "MEDIO SAN JUAN",
    "NUQUÍ",
    "NÓVITA",
    "QUIBDÓ",
    "RIOSUCIO",
    "RÍO IRÓ",
    "RÍO QUITO",
    "SAN JOSÉ DEL PALMAR",
    "SIPÍ",
    "TADÓ",
    "UNGUÍA",
    "UNIÓN PANAMERICANA"
  ],
  "CUNDINAMARCA": [
    "AGUA DE DIOS",
    "ALBÁN",
    "ANAPOIMA",
    "ANOLAIMA",
    "APULO",
    "ARBELÁEZ",
    "BELTRÁN",
    "BITUIMA",
    "BOGOTÁ",
    "BOJACÁ",
    "CABRERA",
    "CACHIPAY",
    "CAJICÁ",
    "CAPARRAPÍ",
    "CARMEN DE CARUPA",
    "CHAGUANÍ",
    "CHIPAQUE",
    "CHOACHÍ",
    "CHOCONTÁ",
    "CHÍA",
    "COGUA",
    "COTA",
    "CUCUNUBÁ",
    "CÁQUEZA",
    "EL COLEGIO",
    "EL PEÑÓN",
    "EL ROSAL",
    "FACATATIVÁ",
    "FOSCA",
    "FUNZA",
    "FUSAGASUGÁ",
    "FÓMEQUE",
    "FÚQUENE",
    "GACHALÁ",
    "GACHANCIPÁ",
    "GACHETÁ",
    "GAMA",
    "GIRARDOT",
    "GRANADA",
    "GUACHETÁ",
    "GUADUAS",
    "GUASCA",
    "GUATAQUÍ",
    "GUATAVITA",
    "GUAYABAL DE SÍQUIMA",
    "GUAYABETAL",
    "GUTIÉRREZ",
    "JERUSALÉN",
    "JUNÍN",
    "LA CALERA",
    "LA MESA",
    "LA PALMA",
    "LA PEÑA",
    "LA VEGA",
    "LENGUAZAQUE",
    "MACHETÁ",
    "MADRID",
    "MANTA",
    "MEDINA",
    "MOSQUERA",
    "NARIÑO",
    "NEMOCÓN",
    "NILO",
    "NIMAIMA",
    "NOCAIMA",
    "PACHO",
    "PAIME",
    "PANDI",
    "PARATEBUENO",
    "PASCA",
    "PUERTO SALGAR",
    "PULÍ",
    "QUEBRADANEGRA",
    "QUETAME",
    "QUIPILE",
    "RICAURTE",
    "SAN ANTONIO DEL TEQUENDAMA",
    "SAN BERNARDO",
    "SAN CAYETANO",
    "SAN FRANCISCO",
    "SAN JUAN DE RIOSECO",
    "SASAIMA",
    "SESQUILÉ",
    "SIBATÉ",
    "SILVANIA",
    "SIMIJACA",
    "SOACHA",
    "SOPÓ",
    "SUBACHOQUE",
    "SUESCA",
    "SUPATÁ",
    "SUSA",
    "SUTATAUSA",
    "TABIO",
    "TAUSA",
    "TENA",
    "TENJO",
    "TIBACUY",
    "TIBIRITA",
    "TOCAIMA",
    "TOCANCIPÁ",
    "TOPAIPÍ",
    "UBALÁ",
    "UBAQUE",
    "UBATÉ",
    "UNE",
    "VENECIA",
    "VERGARA",
    "VIANÍ",
    "VILLAGÓMEZ",
    "VILLAPINZÓN",
    "VILLETA",
    "VIOTÁ",
    "YACOPÍ",
    "ZIPACÓN",
    "ZIPAQUIRÁ",
    "ÚTICA"
  ],
  "CÓRDOBA": [
    "AYAPEL",
    "BUENAVISTA",
    "CANALETE",
    "CERETÉ",
    "CHIMÁ",
    "CHINÚ",
    "CIÉNAGA DE ORO",
    "COTORRA",
    "LA APARTADA",
    "LORICA",
    "LOS CÓRDOBAS",
    "MOMIL",
    "MONTELÍBANO",
    "MONTERÍA",
    "MOÑITOS",
    "PLANETA RICA",
    "PUEBLO NUEVO",
    "PUERTO ESCONDIDO",
    "PUERTO LIBERTADOR",
    "PURÍSIMA",
    "SAHAGÚN",
    "SAN ANDRÉS DE SOTAVENTO",
    "SAN ANTERO",
    "SAN BERNARDO DEL VIENTO",
    "SAN CARLOS",
    "SAN JOSÉ DE URÉ",
    "SAN PELAYO",
    "TIERRALTA",
    "TUCHÍN",
    "VALENCIA"
  ],
  "GUAINÍA": [
    "INÍRIDA"
  ],
  "GUAVIARE": [
    "CALAMAR",
    "EL RETORNO",
    "MIRAFLORES",
    "SAN JOSÉ DEL GUAVIARE"
  ],
  "HUILA": [
    "ACEVEDO",
    "AGRADO",
    "AIPE",
    "ALGECIRAS",
    "ALTAMIRA",
    "BARAYA",
    "CAMPOALEGRE",
    "COLOMBIA",
    "EL PITAL",
    "ELÍAS",
    "GARZÓN",
    "GIGANTE",
    "GUADALUPE",
    "HOBO",
    "ISNOS",
    "LA ARGENTINA",
    "LA PLATA",
    "NEIVA",
    "NÁTAGA",
    "OPORAPA",
    "PAICOL",
    "PALERMO",
    "PALESTINA",
    "PITALITO",
    "RIVERA",
    "SALADOBLANCO",
    "SAN AGUSTÍN",
    "SANTA MARÍA",
    "SUAZA",
    "TARQUI",
    "TELLO",
    "TERUEL",
    "TESALIA",
    "TIMANÁ",
    "VILLAVIEJA",
    "YAGUARÁ",
    "ÍQUIRA"
  ],
  "LA GUAJIRA": [
    "ALBANIA",
    "BARRANCAS",
    "DIBULLA",
    "DISTRACCIÓN",
    "EL MOLINO",
    "FONSECA",
    "HATONUEVO",
    "LA JAGUA DEL PILAR",
    "MAICAO",
    "MANAURE",
    "RIOHACHA",
    "SAN JUAN DEL CESAR",
    "URIBIA",
    "URUMITA",
    "VILLANUEVA"
  ],
  "MAGDALENA": [
    "ALGARROBO",
    "ARACATACA",
    "ARIGUANÍ",
    "CERRO DE SAN ANTONIO",
    "CHIBOLO",
    "CHIBOLO",
    "CIÉNAGA",
    "CONCORDIA",
    "EL BANCO",
    "EL PIÑÓN",
    "EL RETÉN",
    "FUNDACIÓN",
    "GUAMAL",
    "NUEVA GRANADA",
    "PEDRAZA",
    "PIJIÑO DEL CARMEN",
    "PIVIJAY",
    "PLATO",
    "PUEBLO VIEJO",
    "REMOLINO",
    "SABANAS DE SAN ÁNGEL",
    "SALAMINA",
    "SAN SEBASTIÁN DE BUENAVISTA",
    "SAN ZENÓN",
    "SANTA ANA",
    "SANTA BÁRBARA DE PINTO",
    "SANTA MARTA",
    "SITIONUEVO",
    "TENERIFE",
    "ZAPAYÁN",
    "ZONA BANANERA"
  ],
  "META": [
    "ACACÍAS",
    "BARRANCA DE UPÍA",
    "CABUYARO",
    "CASTILLA LA NUEVA",
    "CUBARRAL",
    "CUMARAL",
    "EL CALVARIO",
    "EL CASTILLO",
    "EL DORADO",
    "FUENTE DE ORO",
    "GRANADA",
    "GUAMAL",
    "LA MACARENA",
    "LA URIBE",
    "LEJANÍAS",
    "MAPIRIPÁN",
    "MESETAS",
    "PUERTO CONCORDIA",
    "PUERTO GAITÁN",
    "PUERTO LLERAS",
    "PUERTO LÓPEZ",
    "PUERTO RICO",
    "RESTREPO",
    "SAN CARLOS DE GUAROA",
    "SAN JUAN DE ARAMA",
    "SAN JUANITO",
    "SAN MARTÍN",
    "VILLAVICENCIO",
    "VISTA HERMOSA"
  ],
  "NARIÑO": [
    "ALDANA",
    "ANCUYÁ",
    "ARBOLEDA",
    "BARBACOAS",
    "BELÉN",
    "BUESACO",
    "CHACHAGÜÍ",
    "COLÓN",
    "CONSACÁ",
    "CONTADERO",
    "CUASPUD",
    "CUMBAL",
    "CUMBITARA",
    "CÓRDOBA",
    "EL CHARCO",
    "EL PEÑOL",
    "EL ROSARIO",
    "EL TABLÓN",
    "EL TAMBO",
    "FRANCISCO PIZARRO",
    "FUNES",
    "GUACHUCAL",
    "GUAITARILLA",
    "GUALMATÁN",
    "ILES",
    "IMUÉS",
    "IPIALES",
    "LA CRUZ",
    "LA FLORIDA",
    "LA LLANADA",
    "LA TOLA",
    "LA UNIÓN",
    "LEIVA",
    "LINARES",
    "LOS ANDES",
    "MAGÜÍ PAYÁN",
    "MALLAMA",
    "MOSQUERA",
    "NARIÑO",
    "OLAYA HERRERA",
    "OSPINA",
    "PASTO",
    "POLICARPA",
    "POTOSÍ",
    "PROVIDENCIA",
    "PUERRES",
    "PUPIALES",
    "RICAURTE",
    "ROBERTO PAYÁN",
    "SAMANIEGO",
    "SAN BERNARDO",
    "SAN JOSÉ DE ALBÁN",
    "SAN LORENZO",
    "SAN PABLO",
    "SAN PEDRO DE CARTAGO",
    "SANDONÁ",
    "SANTA BÁRBARA",
    "SANTACRUZ",
    "SAPUYES",
    "TAMINANGO",
    "TANGUA",
    "TUMACO",
    "TÚQUERRES",
    "YACUANQUER"
  ],
  "NORTE DE SANTANDER": [
    "ARBOLEDAS",
    "BOCHALEMA",
    "BUCARASICA",
    "CHINÁCOTA",
    "CHITAGÁ",
    "CONVENCIÓN",
    "CUCUTILLA",
    "CÁCHIRA",
    "CÁCOTA",
    "CÚCUTA",
    "DURANÍA",
    "EL CARMEN",
    "EL TARRA",
    "EL ZULIA",
    "GRAMALOTE",
    "HACARÍ",
    "HERRÁN",
    "LA ESPERANZA",
    "LA PLAYA DE BELÉN",
    "LABATECA",
    "LOS PATIOS",
    "LOURDES",
    "MUTISCUA",
    "OCAÑA",
    "PAMPLONA",
    "PAMPLONITA",
    "PUERTO SANTANDER",
    "RAGONVALIA",
    "SALAZAR DE LAS PALMAS",
    "SAN CALIXTO",
    "SAN CAYETANO",
    "SANTIAGO",
    "SANTO DOMINGO DE SILOS",
    "SARDINATA",
    "TEORAMA",
    "TIBÚ",
    "TOLEDO",
    "VILLA CARO",
    "VILLA DEL ROSARIO",
    "ÁBREGO"
  ]
};
