export const DIVIPOLA_1: Record<string, string[]> = {
  "AMAZONAS": [
    "LETICIA",
    "PUERTO NARIÑO"
  ],
  "ANTIOQUIA": [
    "ABEJORRAL",
    "ABRIAQUÍ",
    "ALEJANDRÍA",
    "AMAGÁ",
    "AMALFI",
    "ANDES",
    "ANGELÓPOLIS",
    "ANGOSTURA",
    "ANORÍ",
    "ANZÁ",
    "APARTADÓ",
    "ARBOLETES",
    "ARGELIA",
    "ARMENIA",
    "BARBOSA",
    "BELLO",
    "BELMIRA",
    "BETANIA",
    "BETULIA",
    "BRICEÑO",
    "BURITICÁ",
    "CAICEDO",
    "CALDAS",
    "CAMPAMENTO",
    "CARACOLÍ",
    "CARAMANTA",
    "CAREPA",
    "CAROLINA DEL PRÍNCIPE",
    "CAUCASIA",
    "CAÑASGORDAS",
    "CHIGORODÓ",
    "CISNEROS",
    "CIUDAD BOLÍVAR",
    "COCORNÁ",
    "CONCEPCIÓN",
    "CONCORDIA",
    "COPACABANA",
    "CÁCERES",
    "DABEIBA",
    "DONMATÍAS",
    "EBÉJICO",
    "EL BAGRE",
    "EL CARMEN DE VIBORAL",
    "EL PEÑOL",
    "EL RETIRO",
    "EL SANTUARIO",
    "ENTRERRÍOS",
    "ENVIGADO",
    "FREDONIA",
    "FRONTINO",
    "GIRALDO",
    "GIRARDOTA",
    "GRANADA",
    "GUADALUPE",
    "GUARNE",
    "GUATAPÉ",
    "GÓMEZ PLATA",
    "HELICONIA",
    "HISPANIA",
    "ITAGÜÍ",
    "ITUANGO",
    "JARDÍN",
    "JERICÓ",
    "LA CEJA",
    "LA ESTRELLA",
    "LA PINTADA",
    "LA UNIÓN",
    "LIBORINA",
    "MACEO",
    "MARINILLA",
    "MEDELLÍN",
    "MONTEBELLO",
    "MURINDÓ",
    "MUTATÁ",
    "NARIÑO",
    "NECHÍ",
    "NECOCLÍ",
    "OLAYA",
    "PEQUE",
    "PUEBLORRICO",
    "PUERTO BERRÍO",
    "PUERTO NARE",
    "PUERTO TRIUNFO",
    "REMEDIOS",
    "RIONEGRO",
    "SABANALARGA",
    "SABANETA",
    "SALGAR",
    "SAN ANDRÉS DE CUERQUIA",
    "SAN CARLOS",
    "SAN FRANCISCO",
    "SAN JERÓNIMO",
    "SAN JOSÉ DE LA MONTAÑA",
    "SAN JUAN DE URABÁ",
    "SAN LUIS",
    "SAN PEDRO DE LOS MILAGROS",
    "SAN PEDRO DE URABÁ",
    "SAN RAFAEL",
    "SAN ROQUE",
    "SAN VICENTE",
    "SANTA BÁRBARA",
    "SANTA FE DE ANTIOQUIA",
    "SANTA ROSA DE OSOS",
    "SANTO DOMINGO",
    "SEGOVIA",
    "SONSÓN",
    "SOPETRÁN",
    "TARAZÁ",
    "TARSO",
    "TITIRIBÍ",
    "TOLEDO",
    "TURBO",
    "TÁMESIS",
    "URAMITA",
    "URRAO",
    "VALDIVIA",
    "VALPARAÍSO",
    "VEGACHÍ",
    "VENECIA",
    "VIGÍA DEL FUERTE",
    "YALÍ",
    "YARUMAL",
    "YOLOMBÓ",
    "YONDÓ",
    "ZARAGOZA"
  ],
  "ARAUCA": [
    "ARAUCA",
    "ARAUQUITA",
    "CRAVO NORTE",
    "FORTUL",
    "PUERTO RONDÓN",
    "SARAVENA",
    "TAME"
  ],
  "ATLÁNTICO": [
    "BARANOA",
    "BARRANQUILLA",
    "CAMPO DE LA CRUZ",
    "CANDELARIA",
    "GALAPA",
    "JUAN DE ACOSTA",
    "LURUACO",
    "MALAMBO",
    "MANATÍ",
    "PALMAR DE VARELA",
    "PIOJÓ",
    "POLONUEVO",
    "PONEDERA",
    "PUERTO COLOMBIA",
    "REPELÓN",
    "SABANAGRANDE",
    "SABANALARGA",
    "SANTA LUCÍA",
    "SANTO TOMÁS",
    "SOLEDAD",
    "SUÁN",
    "TUBARÁ",
    "USIACURÍ"
  ],
  "BOLÍVAR": [
    "ACHÍ",
    "ALTOS DEL ROSARIO",
    "ARENAL",
    "ARJONA",
    "ARROYOHONDO",
    "BARRANCO DE LOBA",
    "BRAZUELO DE PAPAYAL",
    "CALAMAR",
    "CANTAGALLO",
    "CARTAGENA DE INDIAS",
    "CICUCO",
    "CLEMENCIA",
    "CÓRDOBA",
    "EL CARMEN DE BOLÍVAR",
    "EL GUAMO",
    "EL PEÑÓN",
    "HATILLO DE LOBA",
    "MAGANGUÉ",
    "MAHATES",
    "MARGARITA",
    "MARÍA LA BAJA",
    "MOMPÓS",
    "MONTECRISTO",
    "MORALES",
    "NOROSÍ",
    "PINILLOS",
    "REGIDOR",
    "RÍO VIEJO",
    "SAN CRISTÓBAL",
    "SAN ESTANISLAO",
    "SAN FERNANDO",
    "SAN JACINTO",
    "SAN JACINTO DEL CAUCA",
    "SAN JUAN NEPOMUCENO",
    "SAN MARTÍN DE LOBA",
    "SAN PABLO",
    "SANTA CATALINA",
    "SANTA ROSA",
    "SANTA ROSA DEL SUR",
    "SIMITÍ",
    "SOPLAVIENTO",
    "TALAIGUA NUEVO",
    "TIQUISIO",
    "TURBACO",
    "TURBANÁ",
    "VILLANUEVA",
    "ZAMBRANO"
  ],
  "BOYACÁ": [
    "ALMEIDA",
    "AQUITANIA",
    "ARCABUCO",
    "BELÉN",
    "BERBEO",
    "BETÉITIVA",
    "BOAVITA",
    "BOYACÁ",
    "BRICEÑO",
    "BUENAVISTA",
    "BUSBANZÁ",
    "CALDAS",
    "CAMPOHERMOSO",
    "CERINZA",
    "CHINAVITA",
    "CHIQUINQUIRÁ",
    "CHISCAS",
    "CHITA",
    "CHITARAQUE",
    "CHIVATÁ",
    "CHIVOR",
    "CHÍQUIZA",
    "CIÉNEGA",
    "COPER",
    "CORRALES",
    "COVARACHÍA",
    "CUBARÁ",
    "CUCAITA",
    "CUÍTIVA",
    "CÓMBITA",
    "DUITAMA",
    "EL COCUY",
    "EL ESPINO",
    "FIRAVITOBA",
    "FLORESTA",
    "GACHANTIVÁ",
    "GARAGOA",
    "GUACAMAYAS",
    "GUATEQUE",
    "GUAYATÁ",
    "GÁMEZA",
    "GÜICÁN",
    "IZA",
    "JENESANO",
    "JERICÓ",
    "LA CAPILLA",
    "LA UVITA",
    "LA VICTORIA",
    "LABRANZAGRANDE",
    "MACANAL",
    "MARIPÍ",
    "MIRAFLORES",
    "MONGUA",
    "MONGUÍ",
    "MONIQUIRÁ",
    "MOTAVITA",
    "MUZO",
    "NOBSA",
    "NUEVO COLÓN",
    "OICATÁ",
    "OTANCHE",
    "PACHAVITA",
    "PAIPA",
    "PAJARITO",
    "PANQUEBA",
    "PAUNA",
    "PAYA",
    "PAZ DEL RÍO",
    "PESCA",
    "PISBA",
    "PUERTO BOYACÁ",
    "PÁEZ",
    "QUÍPAMA",
    "RAMIRIQUÍ",
    "RONDÓN",
    "RÁQUIRA",
    "SABOYÁ",
    "SAMACÁ",
    "SAN EDUARDO",
    "SAN JOSÉ DE PARE",
    "SAN LUIS DE GACENO",
    "SAN MATEO",
    "SAN MIGUEL DE SEMA",
    "SAN PABLO DE BORBUR",
    "SANTA MARÍA",
    "SANTA ROSA DE VITERBO",
    "SANTA SOFÍA",
    "SANTANA",
    "SATIVANORTE",
    "SATIVASUR",
    "SIACHOQUE",
    "SOATÁ",
    "SOCHA",
    "SOCOTÁ",
    "SOGAMOSO",
    "SOMONDOCO",
    "SORA",
    "SORACÁ",
    "SOTAQUIRÁ",
    "SUSACÓN",
    "SUTAMARCHÁN",
    "SUTATENZA",
    "SÁCHICA",
    "TASCO",
    "TENZA",
    "TIBANÁ",
    "TIBASOSA",
    "TINJACÁ",
    "TIPACOQUE",
    "TOCA",
    "TOGÜÍ",
    "TOTA",
    "TUNJA",
    "TUNUNGUÁ",
    "TURMEQUÉ",
    "TUTA",
    "TUTAZÁ",
    "TÓPAGA",
    "VENTAQUEMADA",
    "VILLA DE LEYVA",
    "VIRACACHÁ",
    "ZETAQUIRA",
    "ÚMBITA"
  ],
  "CALDAS": [
    "AGUADAS",
    "ANSERMA",
    "ARANZAZU",
    "BELALCÁZAR",
    "CHINCHINÁ",
    "FILADELFIA",
    "LA DORADA",
    "LA MERCED",
    "MANIZALES",
    "MANZANARES",
    "MARMATO",
    "MARQUETALIA",
    "MARULANDA",
    "NEIRA",
    "NORCASIA",
    "PALESTINA",
    "PENSILVANIA",
    "PÁCORA",
    "RIOSUCIO",
    "RISARALDA",
    "SALAMINA",
    "SAMANÁ",
    "SAN JOSÉ",
    "SUPÍA",
    "VICTORIA",
    "VILLAMARÍA",
    "VITERBO"
  ],
  "CAQUETÁ": [
    "ALBANIA",
    "BELÉN DE LOS ANDAQUÍES",
    "CARTAGENA DEL CHAIRÁ",
    "CURILLO",
    "EL DONCELLO",
    "EL PAUJIL",
    "FLORENCIA",
    "LA MONTAÑITA",
    "MILÁN",
    "MORELIA",
    "PUERTO RICO",
    "SAN JOSÉ DEL FRAGUA",
    "SAN VICENTE DEL CAGUÁN",
    "SOLANO",
    "SOLITA",
    "VALPARAÍSO"
  ],
  "CASANARE": [
    "AGUAZUL",
    "CHÁMEZA",
    "HATO COROZAL",
    "LA SALINA",
    "MANÍ",
    "MONTERREY",
    "NUNCHÍA",
    "OROCUÉ",
    "PAZ DE ARIPORO",
    "PORE",
    "RECETOR",
    "SABANALARGA",
    "SAN LUIS DE PALENQUE",
    "SÁCAMA",
    "TAURAMENA",
    "TRINIDAD",
    "TÁMARA",
    "VILLANUEVA",
    "YOPAL"
  ],
  "CAUCA": [
    "ALMAGUER",
    "ARGELIA",
    "BALBOA",
    "BOLÍVAR",
    "BUENOS AIRES",
    "CAJIBÍO",
    "CALDONO",
    "CALOTO",
    "CORINTO",
    "EL TAMBO",
    "FLORENCIA",
    "GUACHENÉ",
    "GUAPÍ",
    "INZÁ",
    "JAMBALÓ",
    "LA SIERRA",
    "LA VEGA",
    "LÓPEZ DE MICAY",
    "MERCADERES",
    "MIRANDA",
    "MORALES",
    "PADILLA",
    "PATÍA",
    "PIAMONTE",
    "PIENDAMÓ",
    "POPAYÁN",
    "PUERTO TEJADA",
    "PURACÉ",
    "PÁEZ",
    "ROSAS",
    "SAN SEBASTIÁN",
    "SANTA ROSA",
    "SANTANDER DE QUILICHAO",
    "SILVIA",
    "SOTARÁ",
    "SUCRE",
    "SUÁREZ",
    "TIMBIQUÍ",
    "TIMBÍO",
    "TORIBÍO",
    "TOTORÓ",
    "VILLA RICA"
  ],
  "CESAR": [
    "AGUACHICA",
    "AGUSTÍN CODAZZI",
    "ASTREA",
    "BECERRIL",
    "BOSCONIA",
    "CHIMICHAGUA",
    "CHIRIGUANÁ",
    "CURUMANÍ",
    "EL COPEY",
    "EL PASO",
    "GAMARRA",
    "GONZÁLEZ",
    "LA GLORIA (CESAR)",
    "LA JAGUA DE IBIRICO",
    "LA PAZ",
    "MANAURE BALCÓN DEL CESAR",
    "PAILITAS",
    "PELAYA",
    "PUEBLO BELLO",
    "RÍO DE ORO",
    "SAN ALBERTO",
    "SAN DIEGO",
    "SAN MARTÍN",
    "TAMALAMEQUE",
    "VALLEDUPAR"
  ]
};
