from typing import List, Dict, Any

# ==========================================
# MANIFIESTO CENTRAL DE MÓDULOS DEL SISTEMA
# ==========================================
# Single Source of Truth (SSOT) para el sistema RBAC.
# El backend auto-sincronizará esta lista con la base de datos
# en cada arranque (Upsert) conservando nombres editados por UI.
# ==========================================

SYSTEM_MODULES_REGISTRY: List[Dict[str, Any]] = [
    # --- CATEGORÍA: PORTAL (Módulos de Cara al Usuario) ---
    {
        "id": "service-portal",
        "nombre": "Portal de Servicios (Shell)",
        "categoria": "portal",
        "es_critico": True,
        "descripcion": "Portal de entrada y shell principal de redirección a los distintos servicios de TI.",
    },
    {
        "id": "mis_solicitudes",
        "nombre": "Gestión de Solicitudes TI",
        "categoria": "portal",
        "es_critico": True,
        "descripcion": "Bandeja del usuario final para crear nuevos requerimientos de soporte y hacer seguimiento de sus tickets activos.",
    },
    {
        "id": "reserva_salas",
        "nombre": "Reserva de salas",
        "categoria": "portal",
        "es_critico": False,
        "descripcion": "Gestión de reservas de salas de reuniones y espacios colaborativos para el equipo.",
    },
    {
        "id": "requisiciones",
        "nombre": "Sistema de Solicitudes",
        "categoria": "portal",
        "es_critico": True,
        "descripcion": "Creación, seguimiento y flujo de aprobación para solicitudes de compras corporativas.",
    },
    {
        "id": "requisiciones.almacen",
        "nombre": "Requisiciones - Almacén",
        "categoria": "portal",
        "es_critico": True,
        "descripcion": "Formulario de solicitud de consumibles de papelería, dotación del personal y hardware disponible en almacén.",
    },
    {
        "id": "requisiciones.presupuesto",
        "nombre": "Requisiciones - Presupuesto",
        "categoria": "portal",
        "es_critico": False,
        "descripcion": "Modulo para la evaluación presupuestal de la compañía y aprobación de gastos mayores.",
    },
    {
        "id": "viaticos_gestion",
        "nombre": "Gestión de Viáticos",
        "categoria": "portal",
        "es_critico": True,
        "descripcion": "Portal de solicitudes de anticipos y legalizaciones de gastos asociados a viajes corporativos.",
    },
    {
        "id": "viaticos_estado",
        "nombre": "Estado de Cuenta",
        "categoria": "portal",
        "es_critico": True,
        "descripcion": "Consulta de saldos pendientes, estados de legalizaciones y estado de cuenta contable con Tesorería.",
    },
    {
        "id": "sistemas",
        "nombre": "Soporte Sistemas",
        "categoria": "portal",
        "es_critico": False,
        "descripcion": "Acceso directo a la radicación de requerimientos en el portal de soporte técnico de hardware y software.",
    },
    {
        "id": "mejoramiento",
        "nombre": "Mejoramiento TI",
        "categoria": "portal",
        "es_critico": False,
        "descripcion": "Canal de radicación para proyectos de optimización de procesos internos y mejoramiento continuo de TI.",
    },
    {
        "id": "desarrollo",
        "nombre": "Software Factory",
        "categoria": "portal",
        "es_critico": False,
        "descripcion": "Software Factory para el control detallado del ciclo de vida y sprints en desarrollos a medida.",
    },
    {
        "id": "chat",
        "nombre": "Asistente IA",
        "categoria": "portal",
        "es_critico": False,
        "descripcion": "Asistente inteligente interactivo con IA para responder consultas de operación.",
    },
    {
        "id": "gestion_humana",
        "nombre": "Gestión Humana",
        "categoria": "portal",
        "es_critico": False,
        "descripcion": "Módulo para la consulta de certificados laborales, desprendibles de nómina y documentación de retenciones.",
    },
    {
        "id": "requisicion_personal",
        "nombre": "Requisición de Personal",
        "categoria": "portal",
        "es_critico": False,
        "descripcion": "Creación y seguimiento de solicitudes de contratación de personal.",
    },
    {
        "id": "perfiles_cargo",
        "nombre": "Perfiles de Cargo",
        "categoria": "portal",
        "es_critico": False,
        "descripcion": "Administración de áreas, cargos y sus relaciones de reporte jerárquico.",
    },

    # --- CATEGORÍA: ANALISTAS (Herramientas de Operación TI) ---
    {
        "id": "dashboard",
        "nombre": "Tablero Principal",
        "categoria": "analistas",
        "es_critico": True,
        "descripcion": "Muro centralizado de control de mando con KPIs y estado de la operación diaria del departamento.",
    },
    {
        "id": "ticket-management",
        "nombre": "Gestión de Tickets",
        "categoria": "analistas",
        "es_critico": False,
        "descripcion": "Módulo de gestión del analista de soporte para asignar, tipificar y resolver tickets de incidencias.",
    },
    {
        "id": "developments",
        "nombre": "Gestión de Actividades",
        "categoria": "analistas",
        "es_critico": False,
        "descripcion": "Planificación de hitos, asignación de tareas y seguimiento a los analistas en la Software Factory.",
    },
    {
        "id": "indicators",
        "nombre": "Indicadores Globales (BI)",
        "categoria": "analistas",
        "es_critico": False,
        "descripcion": "Módulo de Business Intelligence (BI) para visualizar desviaciones y métricas de rendimiento histórico de TI.",
    },
    {
        "id": "reports",
        "nombre": "Reportería Avanzada",
        "categoria": "analistas",
        "es_critico": False,
        "descripcion": "Exportación y generación de informes parametrizados de tickets, viáticos y rendimiento de analistas.",
    },
    {
        "id": "validaciones_asignacion",
        "nombre": "Aprobaciones de Asignación",
        "categoria": "analistas",
        "es_critico": False,
        "descripcion": "Bandeja de decisiones para aprobar o rechazar comisiones y viáticos de personal jerárquicamente indirecto.",
    },
    {
        "id": "jerarquia_organizacional",
        "nombre": "Jerarquía Organizacional",
        "categoria": "analistas",
        "es_critico": False,
        "descripcion": "Definición del organigrama institucional que rige las aprobaciones y conducto regular del sistema.",
    },
    {
        "id": "settings",
        "nombre": "Parámetros del Sistema",
        "categoria": "analistas",
        "es_critico": False,
        "descripcion": "Configuración de variables del sistema, niveles de servicio y parámetros operativos.",
    },
    {
        "id": "viaticos_reportes",
        "nombre": "Reportes de Tránsito",
        "categoria": "analistas",
        "es_critico": False,
        "descripcion": "Bandeja de analistas para consolidar y exportar legalizaciones autorizadas a la tabla de tránsito del ERP.",
    },
    {
        "id": "wbs_templates",
        "nombre": "Plantillas de Proyectos (WBS)",
        "categoria": "analistas",
        "es_critico": False,
        "descripcion": "Diseño de plantillas de desglose de trabajo (WBS) para estandarizar las fases de nuevos proyectos.",
    },
    {
        "id": "lineas_corporativas",
        "nombre": "Gestión de Líneas Corporativas",
        "categoria": "analistas",
        "es_critico": False,
        "descripcion": "Control, asignación y auditoría de consumos de planes de telefonía móvil y líneas de datos corporativas.",
    },

    # --- CATEGORÍA: PANEL (Administración de Control) ---
    {
        "id": "control-tower",
        "nombre": "Torre de Control",
        "categoria": "panel",
        "es_critico": True,
        "descripcion": "Torre de control en tiempo real para monitoreo de logs, salud de servidores e integraciones API.",
    },
    {
        "id": "panel_maestro",
        "nombre": "Panel Maestro",
        "categoria": "panel",
        "es_critico": True,
        "descripcion": "Consola de parametrización troncal y mantenimiento maestro de seguridad del sistema.",
    },
    {
        "id": "admin_usuarios",
        "nombre": "Gestor de Usuarios",
        "categoria": "panel",
        "es_critico": True,
        "descripcion": "Asignación de perfiles, activación de usuarios y control inicial de acceso.",
    },
    {
        "id": "user-admin",
        "nombre": "Administración de Usuarios",
        "categoria": "panel",
        "es_critico": True,
        "descripcion": "Gestión granular de cuentas de usuario, asignación de roles y desbloqueo de rate limits.",
    },
    {
        "id": "admin_roles",
        "nombre": "Gestor de Roles y Permisos",
        "categoria": "panel",
        "es_critico": True,
        "descripcion": "Consola de configuración de la matriz de permisos de seguridad por rol utilizando el middleware dinámico RBAC.",
    },
    {
        "id": "viaticos_director_panel",
        "nombre": "Panel de Aprobación (Directores)",
        "categoria": "panel",
        "es_critico": True,
        "descripcion": "Bandeja de aprobaciones exclusiva para directores de área para autorizar viáticos de su personal directo.",
    },
    {
        "id": "reserva_salas_admin",
        "nombre": "Administración de Salas",
        "categoria": "panel",
        "es_critico": False,
        "descripcion": "Configuración y mantenimiento de salas de conferencias, sus recursos tecnológicos y horarios de operación.",
    },
    {
        "id": "design-catalog",
        "nombre": "Catálogo de Diseño UI/UX",
        "categoria": "panel",
        "es_critico": False,
        "descripcion": "Catálogo estándar de elementos UX/UI, átomos y moléculas de diseño del frontend.",
    },
    {
        "id": "inventario_anual",
        "nombre": "Inventario Anual",
        "categoria": "panel",
        "es_critico": True,
        "descripcion": "Planificación, fechas de cierre y control del proceso de inventario anual de activos de TI.",
    },
    {
        "id": "inventario_2026",
        "nombre": "Inventario 2026 (Digitalización)",
        "categoria": "portal",
        "es_critico": True,
        "descripcion": "Interfaz de digitalización y captura rápida de códigos de barras de hardware para operarios de inventario.",
    },
    {
        "id": "comisiones",
        "nombre": "Gestión de Comisiones",
        "categoria": "portal",
        "es_critico": True,
        "descripcion": "Cálculo, liquidación periódica y procesamiento de comisiones comerciales para los asesores del personal.",
    },
    {
        "id": "nomina_novedades",
        "nombre": "Novedades de Nómina",
        "categoria": "portal",
        "es_critico": True,
        "descripcion": "Carga y procesamiento de novedades de personal (incapacidades, horas extra, recargos) destinadas al sistema de nómina SOLID.",
    },
    {
        "id": "configuracion_centro_costo",
        "nombre": "Configuración Centros de Costos",
        "categoria": "panel",
        "es_critico": False,
        "descripcion": "Configuración de catálogos de UEN, Subcentro de Costos y Especialidad en el ERP.",
    },
]
