"""Init_Spanish_Schema

Revision ID: 1918967cf7ca
Revises: 
Create Date: 2025-12-26 20:12:48.232344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '1918967cf7ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('nit', sa.String(), nullable=True),
    sa.Column('inicio_jornada_nocturna', sa.String(), nullable=True),
    sa.Column('meta_horas_semanales', sa.Integer(), nullable=True),
    sa.Column('factor_nomina', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nit'), 'empresas', ['nit'], unique=True)
    op.create_index(op.f('ix_empresas_nombre'), 'empresas', ['nombre'], unique=True)
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('codigo_erp', sa.String(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('presupuesto_dinero', sa.Float(), nullable=True),
    sa.Column('presupuesto_horas', sa.Float(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('radio_geocerca', sa.Float(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyectos_codigo_erp'), 'proyectos', ['codigo_erp'], unique=True)
    op.create_index(op.f('ix_proyectos_id'), 'proyectos', ['id'], unique=False)
    op.create_index(op.f('ix_proyectos_nombre'), 'proyectos', ['nombre'], unique=False)
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('numero_documento', sa.String(), nullable=True),
    sa.Column('salario_base', sa.Float(), nullable=True),
    sa.Column('valor_hora', sa.Float(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.Column('plantilla_biometrica', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleados_id'), 'empleados', ['id'], unique=False)
    op.create_index(op.f('ix_empleados_numero_documento'), 'empleados', ['numero_documento'], unique=True)
    op.create_table('novedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('url_adjunto', sa.String(), nullable=True),
    sa.Column('es_paga', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novedades_fecha_fin'), 'novedades', ['fecha_fin'], unique=False)
    op.create_index(op.f('ix_novedades_fecha_inicio'), 'novedades', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_novedades_id'), 'novedades', ['id'], unique=False)
    op.create_index(op.f('ix_novedades_tipo'), 'novedades', ['tipo'], unique=False)
    op.create_table('registros_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.Column('es_valido', sa.Boolean(), nullable=True),
    sa.Column('puntaje_facial', sa.Float(), nullable=True),
    sa.Column('ruta_foto', sa.String(), nullable=True),
    sa.Column('motivo_falla', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_asistencia_id'), 'registros_asistencia', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_registros_asistencia_id'), table_name='registros_asistencia')
    op.drop_table('registros_asistencia')
    op.drop_index(op.f('ix_novedades_tipo'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_id'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_fecha_inicio'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_fecha_fin'), table_name='novedades')
    op.drop_table('novedades')
    op.drop_index(op.f('ix_empleados_numero_documento'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_id'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_index(op.f('ix_proyectos_nombre'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_id'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_codigo_erp'), table_name='proyectos')
    op.drop_table('proyectos')
    op.drop_index(op.f('ix_empresas_nombre'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_nit'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
