"""add_responsible_field_to_developments

Revision ID: 812831bb3379
Revises: bf7a0f78089c
Create Date: 2025-09-17 13:35:59.387558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812831bb3379'
down_revision = 'bf7a0f78089c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developments', sa.Column('responsible', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developments', 'responsible')
    # ### end Alembic commands ###
