"""complete_spanish_localization

Revision ID: c89945b74bcd
Revises: 870a12d5f838
Create Date: 2026-01-08 19:57:29.049460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c89945b74bcd'
down_revision = '870a12d5f838'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_control_calidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_code', sa.String(length=20), nullable=False),
    sa.Column('control_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stage_prefix', sa.String(length=50), nullable=False),
    sa.Column('stage_description', sa.String(length=255), nullable=True),
    sa.Column('deliverables', sa.Text(), nullable=True),
    sa.Column('validation_criteria', sa.Text(), nullable=True),
    sa.Column('responsible_party', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_code')
    )
    op.create_index(op.f('ix_catalogo_control_calidad_id'), 'catalogo_control_calidad', ['id'], unique=False)
    op.create_table('categorias_ticket',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('form_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuraciones_modelo_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('cost_per_input_token', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('cost_per_output_token', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.Text(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_index(op.f('ix_configuraciones_modelo_ia_id'), 'configuraciones_modelo_ia', ['id'], unique=False)
    op.create_table('fases_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_name', sa.String(length=100), nullable=False),
    sa.Column('phase_description', sa.Text(), nullable=True),
    sa.Column('phase_color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fases_desarrollo_id'), 'fases_desarrollo', ['id'], unique=False)
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_table('usuarios_autenticacion',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_autenticacion_email'), 'usuarios_autenticacion', ['email'], unique=True)
    op.create_table('configuraciones_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios_autenticacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuraciones_sistema_id'), 'configuraciones_sistema', ['id'], unique=False)
    op.create_table('etapas_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('stage_code', sa.String(length=20), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=False),
    sa.Column('stage_description', sa.Text(), nullable=True),
    sa.Column('is_milestone', sa.Boolean(), nullable=True),
    sa.Column('estimated_days', sa.Integer(), nullable=True),
    sa.Column('responsible_party', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['fases_desarrollo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etapas_desarrollo_id'), 'etapas_desarrollo', ['id'], unique=False)
    op.create_table('metricas_uso_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('context_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_partition', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios_autenticacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricas_uso_ia_id'), 'metricas_uso_ia', ['id'], unique=False)
    op.create_table('permisos_rol',
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permisos.id'], ),
    sa.PrimaryKeyConstraint('role', 'permission_id')
    )
    op.create_table('sesiones_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios_autenticacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_chat_id'), 'sesiones_chat', ['id'], unique=False)
    op.create_table('sesiones_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios_autenticacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index(op.f('ix_sesiones_usuario_id'), 'sesiones_usuario', ['id'], unique=False)
    op.create_table('tickets_soporte',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('creator_id', sa.String(length=50), nullable=False),
    sa.Column('creator_name', sa.String(length=255), nullable=True),
    sa.Column('creator_email', sa.String(length=255), nullable=True),
    sa.Column('creator_area', sa.String(length=100), nullable=True),
    sa.Column('creator_cargo', sa.String(length=100), nullable=True),
    sa.Column('creator_sede', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('diagnostic', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('time_spent_hours', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ideal_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categorias_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens_autenticacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios_autenticacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_autenticacion_id'), 'tokens_autenticacion', ['id'], unique=False)
    op.create_table('comentarios_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_soporte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_ticket_id'), 'comentarios_ticket', ['id'], unique=False)
    op.create_table('desarrollos',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('environment', sa.String(length=100), nullable=True),
    sa.Column('remedy_link', sa.Text(), nullable=True),
    sa.Column('current_phase_id', sa.Integer(), nullable=True),
    sa.Column('current_stage_id', sa.Integer(), nullable=True),
    sa.Column('stage_progress_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('general_status', sa.String(length=50), nullable=True),
    sa.Column('estimated_end_date', sa.Date(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_phase_id'], ['fases_desarrollo.id'], ),
    sa.ForeignKeyConstraint(['current_stage_id'], ['etapas_desarrollo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sesiones_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_chat_id'), 'mensajes_chat', ['id'], unique=False)
    op.create_table('cache_contexto_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_key', sa.String(length=255), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=True),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_contexto_ia_context_key'), 'cache_contexto_ia', ['context_key'], unique=True)
    op.create_index(op.f('ix_cache_contexto_ia_id'), 'cache_contexto_ia', ['id'], unique=False)
    op.create_table('controles_calidad_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('control_catalog_id', sa.Integer(), nullable=False),
    sa.Column('control_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('completed_by', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by', sa.String(length=255), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deliverables_provided', sa.Text(), nullable=True),
    sa.Column('deliverables_completed', sa.Text(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('evidence_files', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['control_catalog_id'], ['catalogo_control_calidad.id'], ),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controles_calidad_desarrollo_id'), 'controles_calidad_desarrollo', ['id'], unique=False)
    op.create_table('fechas_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('date_type', sa.String(length=50), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('days_estimated', sa.Integer(), nullable=True),
    sa.Column('days_actual', sa.Integer(), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('functionality_count', sa.Integer(), nullable=True),
    sa.Column('production_deployment_date', sa.Date(), nullable=True),
    sa.Column('delivery_compliance_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fechas_desarrollo_id'), 'fechas_desarrollo', ['id'], unique=False)
    op.create_table('funcionalidades_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('functionality_name', sa.String(length=255), nullable=False),
    sa.Column('functionality_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('defects_count', sa.Integer(), nullable=True),
    sa.Column('test_coverage_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('complexity_level', sa.String(length=20), nullable=True),
    sa.Column('estimated_hours', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('actual_hours', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionalidades_desarrollo_id'), 'funcionalidades_desarrollo', ['id'], unique=False)
    op.create_table('historial_analisis_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=True),
    sa.Column('analysis_type', sa.String(length=100), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('context_used', sa.JSON(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('ai_model', sa.String(length=50), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios_autenticacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_analisis_ia_id'), 'historial_analisis_ia', ['id'], unique=False)
    op.create_table('historial_entregas_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('delivery_version', sa.String(length=50), nullable=True),
    sa.Column('delivery_type', sa.String(length=50), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('return_reason', sa.Text(), nullable=True),
    sa.Column('return_count', sa.Integer(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('quality_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('defects_reported', sa.Integer(), nullable=True),
    sa.Column('defects_resolved', sa.Integer(), nullable=True),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_entregas_desarrollo_id'), 'historial_entregas_desarrollo', ['id'], unique=False)
    op.create_table('historial_estados_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_stage', sa.String(length=100), nullable=True),
    sa.Column('change_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_desarrollo_id'), 'historial_estados_desarrollo', ['id'], unique=False)
    op.create_table('incidentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('impact', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('is_production_derived', sa.Boolean(), nullable=True),
    sa.Column('incident_type', sa.String(length=50), nullable=True),
    sa.Column('severity_level', sa.String(length=20), nullable=True),
    sa.Column('response_time_hours', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('resolution_time_hours', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('is_rework', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidentes_id'), 'incidentes', ['id'], unique=False)
    op.create_table('log_actividades_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_follow_up_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dynamic_payload', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['etapas_desarrollo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_actividades_desarrollo_id'), 'log_actividades_desarrollo', ['id'], unique=False)
    op.create_table('metricas_calidad_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('target_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('calculation_method', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('calculated_by', sa.String(length=255), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricas_calidad_desarrollo_id'), 'metricas_calidad_desarrollo', ['id'], unique=False)
    op.create_table('metricas_kpi_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('target_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('calculated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricas_kpi_desarrollo_id'), 'metricas_kpi_desarrollo', ['id'], unique=False)
    op.create_table('observaciones_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('observation_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('observation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observaciones_desarrollo_id'), 'observaciones_desarrollo', ['id'], unique=False)
    op.create_table('propuestas_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('proposal_number', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propuestas_desarrollo_id'), 'propuestas_desarrollo', ['id'], unique=False)
    op.create_table('proveedores_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('side_service_point', sa.String(length=100), nullable=True),
    sa.Column('provider_system', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_desarrollo_id'), 'proveedores_desarrollo', ['id'], unique=False)
    op.create_table('proximas_actividades_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('responsible_party', sa.String(length=100), nullable=False),
    sa.Column('responsible_person', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proximas_actividades_desarrollo_id'), 'proximas_actividades_desarrollo', ['id'], unique=False)
    op.create_table('recomendaciones_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=True),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('impact_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('effort_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('ai_confidence', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('implementation_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results_feedback', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendaciones_ia_id'), 'recomendaciones_ia', ['id'], unique=False)
    op.create_table('registros_actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_actividad_id'), 'registros_actividad', ['id'], unique=False)
    op.create_table('responsables_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsables_desarrollo_id'), 'responsables_desarrollo', ['id'], unique=False)
    op.create_table('resultados_pruebas_desarrollo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('development_id', sa.String(length=50), nullable=False),
    sa.Column('functionality_id', sa.Integer(), nullable=True),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('test_phase', sa.String(length=50), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('test_status', sa.String(length=50), nullable=True),
    sa.Column('defects_found', sa.Integer(), nullable=True),
    sa.Column('defects_severity', sa.String(length=50), nullable=True),
    sa.Column('test_coverage', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('execution_time_hours', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('tester_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['development_id'], ['desarrollos.id'], ),
    sa.ForeignKeyConstraint(['functionality_id'], ['funcionalidades_desarrollo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultados_pruebas_desarrollo_id'), 'resultados_pruebas_desarrollo', ['id'], unique=False)
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_registros_asistencia_id'), table_name='registros_asistencia')
    op.drop_table('registros_asistencia')
    op.drop_index(op.f('ix_novedades_fecha_fin'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_fecha_inicio'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_id'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_tipo'), table_name='novedades')
    op.drop_table('novedades')
    op.drop_index(op.f('ix_empleados_id'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_numero_documento'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_index(op.f('ix_proyectos_codigo_erp'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_id'), table_name='proyectos')
    op.drop_index(op.f('ix_proyectos_nombre'), table_name='proyectos')
    op.drop_table('proyectos')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_nit'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_nombre'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('empresas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inicio_jornada_nocturna', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meta_horas_semanales', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('factor_nomina', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='empresas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_empresas_nombre'), 'empresas', ['nombre'], unique=True)
    op.create_index(op.f('ix_empresas_nit'), 'empresas', ['nit'], unique=True)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_table('proyectos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('proyectos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('codigo_erp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('presupuesto_dinero', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('presupuesto_horas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitud', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitud', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('radio_geocerca', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('esta_activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='proyectos_empresa_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='proyectos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_proyectos_nombre'), 'proyectos', ['nombre'], unique=False)
    op.create_index(op.f('ix_proyectos_id'), 'proyectos', ['id'], unique=False)
    op.create_index(op.f('ix_proyectos_codigo_erp'), 'proyectos', ['codigo_erp'], unique=True)
    op.create_table('novedades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empleado_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url_adjunto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('es_paga', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], name=op.f('novedades_empleado_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('novedades_pkey'))
    )
    op.create_index(op.f('ix_novedades_tipo'), 'novedades', ['tipo'], unique=False)
    op.create_index(op.f('ix_novedades_id'), 'novedades', ['id'], unique=False)
    op.create_index(op.f('ix_novedades_fecha_inicio'), 'novedades', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_novedades_fecha_fin'), 'novedades', ['fecha_fin'], unique=False)
    op.create_table('empleados',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('empleados_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('apellido', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('numero_documento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salario_base', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_hora', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('proyecto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('esta_activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('plantilla_biometrica', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], name='empleados_proyecto_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='empleados_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_empleados_numero_documento'), 'empleados', ['numero_documento'], unique=True)
    op.create_index(op.f('ix_empleados_id'), 'empleados', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nombre_completo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('esta_activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('empleado_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], name=op.f('usuarios_empleado_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey'))
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('registros_asistencia',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empleado_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('proyecto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_hora', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gps_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gps_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('es_valido', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('puntaje_facial', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ruta_foto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('motivo_falla', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], name=op.f('registros_asistencia_empleado_id_fkey')),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], name=op.f('registros_asistencia_proyecto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('registros_asistencia_pkey'))
    )
    op.create_index(op.f('ix_registros_asistencia_id'), 'registros_asistencia', ['id'], unique=False)
    op.drop_index(op.f('ix_resultados_pruebas_desarrollo_id'), table_name='resultados_pruebas_desarrollo')
    op.drop_table('resultados_pruebas_desarrollo')
    op.drop_index(op.f('ix_responsables_desarrollo_id'), table_name='responsables_desarrollo')
    op.drop_table('responsables_desarrollo')
    op.drop_index(op.f('ix_registros_actividad_id'), table_name='registros_actividad')
    op.drop_table('registros_actividad')
    op.drop_index(op.f('ix_recomendaciones_ia_id'), table_name='recomendaciones_ia')
    op.drop_table('recomendaciones_ia')
    op.drop_index(op.f('ix_proximas_actividades_desarrollo_id'), table_name='proximas_actividades_desarrollo')
    op.drop_table('proximas_actividades_desarrollo')
    op.drop_index(op.f('ix_proveedores_desarrollo_id'), table_name='proveedores_desarrollo')
    op.drop_table('proveedores_desarrollo')
    op.drop_index(op.f('ix_propuestas_desarrollo_id'), table_name='propuestas_desarrollo')
    op.drop_table('propuestas_desarrollo')
    op.drop_index(op.f('ix_observaciones_desarrollo_id'), table_name='observaciones_desarrollo')
    op.drop_table('observaciones_desarrollo')
    op.drop_index(op.f('ix_metricas_kpi_desarrollo_id'), table_name='metricas_kpi_desarrollo')
    op.drop_table('metricas_kpi_desarrollo')
    op.drop_index(op.f('ix_metricas_calidad_desarrollo_id'), table_name='metricas_calidad_desarrollo')
    op.drop_table('metricas_calidad_desarrollo')
    op.drop_index(op.f('ix_log_actividades_desarrollo_id'), table_name='log_actividades_desarrollo')
    op.drop_table('log_actividades_desarrollo')
    op.drop_index(op.f('ix_incidentes_id'), table_name='incidentes')
    op.drop_table('incidentes')
    op.drop_index(op.f('ix_historial_estados_desarrollo_id'), table_name='historial_estados_desarrollo')
    op.drop_table('historial_estados_desarrollo')
    op.drop_index(op.f('ix_historial_entregas_desarrollo_id'), table_name='historial_entregas_desarrollo')
    op.drop_table('historial_entregas_desarrollo')
    op.drop_index(op.f('ix_historial_analisis_ia_id'), table_name='historial_analisis_ia')
    op.drop_table('historial_analisis_ia')
    op.drop_index(op.f('ix_funcionalidades_desarrollo_id'), table_name='funcionalidades_desarrollo')
    op.drop_table('funcionalidades_desarrollo')
    op.drop_index(op.f('ix_fechas_desarrollo_id'), table_name='fechas_desarrollo')
    op.drop_table('fechas_desarrollo')
    op.drop_index(op.f('ix_controles_calidad_desarrollo_id'), table_name='controles_calidad_desarrollo')
    op.drop_table('controles_calidad_desarrollo')
    op.drop_index(op.f('ix_cache_contexto_ia_id'), table_name='cache_contexto_ia')
    op.drop_index(op.f('ix_cache_contexto_ia_context_key'), table_name='cache_contexto_ia')
    op.drop_table('cache_contexto_ia')
    op.drop_index(op.f('ix_mensajes_chat_id'), table_name='mensajes_chat')
    op.drop_table('mensajes_chat')
    op.drop_table('desarrollos')
    op.drop_index(op.f('ix_comentarios_ticket_id'), table_name='comentarios_ticket')
    op.drop_table('comentarios_ticket')
    op.drop_index(op.f('ix_tokens_autenticacion_id'), table_name='tokens_autenticacion')
    op.drop_table('tokens_autenticacion')
    op.drop_table('tickets_soporte')
    op.drop_index(op.f('ix_sesiones_usuario_id'), table_name='sesiones_usuario')
    op.drop_table('sesiones_usuario')
    op.drop_index(op.f('ix_sesiones_chat_id'), table_name='sesiones_chat')
    op.drop_table('sesiones_chat')
    op.drop_table('permisos_rol')
    op.drop_index(op.f('ix_metricas_uso_ia_id'), table_name='metricas_uso_ia')
    op.drop_table('metricas_uso_ia')
    op.drop_index(op.f('ix_etapas_desarrollo_id'), table_name='etapas_desarrollo')
    op.drop_table('etapas_desarrollo')
    op.drop_index(op.f('ix_configuraciones_sistema_id'), table_name='configuraciones_sistema')
    op.drop_table('configuraciones_sistema')
    op.drop_index(op.f('ix_usuarios_autenticacion_email'), table_name='usuarios_autenticacion')
    op.drop_table('usuarios_autenticacion')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_table('permisos')
    op.drop_index(op.f('ix_fases_desarrollo_id'), table_name='fases_desarrollo')
    op.drop_table('fases_desarrollo')
    op.drop_index(op.f('ix_configuraciones_modelo_ia_id'), table_name='configuraciones_modelo_ia')
    op.drop_table('configuraciones_modelo_ia')
    op.drop_table('categorias_ticket')
    op.drop_index(op.f('ix_catalogo_control_calidad_id'), table_name='catalogo_control_calidad')
    op.drop_table('catalogo_control_calidad')
    # ### end Alembic commands ###
