events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        listen 80;
        listen 443 ssl;
        server_name portalservicios.refridcol.com portalservicios.refridcol 192.168.0.21 localhost; # [CONTROLADO]

        # Configuración de Certificados
        ssl_certificate /etc/nginx/certs/gestorti.crt;
        ssl_certificate_key /etc/nginx/certs/gestorti.key;

        # Optimización SSL
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Endpoint de Exportación a Excel (Expuesto directamente)
        location = /api/v2/viaticos/estado-cuenta/xlsx {
            proxy_pass http://backend:8000/api/v2/viaticos/estado-cuenta/xlsx;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;
            
            # Opcional: Aumentar timeout para archivos pesados
            proxy_read_timeout 30s;
        }

        # Proxy para el resto del Backend (API General)
        location /api/v2/ {
            proxy_pass http://backend:8000/api/v2/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;

            # Soporte para WebSockets
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            
            # Optimización para WebSockets
            proxy_buffering off;
            proxy_cache_bypass $http_upgrade;
            
            # Aumentar timeouts para mantener el socket abierto
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }

        # Proxy para el Frontend (Nginx de producción)
        location / {
            proxy_pass http://frontend:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
