CREATE ROLE gestor_test_owner NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE gestor_test_migrator LOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD 'migrator_test_only';
CREATE ROLE gestor_test_runtime LOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD 'runtime_test_only';
GRANT gestor_test_owner TO gestor_test_migrator;
GRANT CONNECT ON DATABASE project_manager_test TO gestor_test_migrator, gestor_test_runtime;
ALTER SCHEMA public OWNER TO gestor_test_owner;
GRANT USAGE ON SCHEMA public TO gestor_test_runtime;
